Slightly Improved Interface
hadess/flatpak-games pull request #15
Opened 2017-04-20 09:24 UTC by andklapp

In general, these changes make game-to-flatpak a bit easier to use. I've introduced a few new options, clarified one, and added informational print statements before and after things that often take a while.

Specifically, I added the --repo option to export games to a directory more useful than just 'repo'. I made the --bundle option automatically delete the repo directory it exports to unless the --repo option is defined. Adding the --keep-repo option seemed necessary so that users could both export to a repo and get a bundle in one command. I changed the --keep-files option to --keep-build-dir to make it clear that it is not the repo files that will be deleted. 

I also added print statements before the verification, unpacking, and copying steps because they can take quite some time with large game files.

Furthermore, I moved the deletion of the build directory to just after the build-export function is called so that if the --bundle option is passed, it will only take up double the game's worth of disk space at once, not triple.

Lastly, I have updated the README to reflect these changes and fixed some of the apparent formatting mistakes.

2017-04-25 10:10 UTC, hadess requested changes

2017-04-25 10:10 UTC, hadess commented on game-to-flatpak
> +	print("game-to-flatpak [--network] [--bundle] [--keep-build-dir] [--keep-repo-dir] [FILE...]")
This commit should be split into 2 separate ones, one for each of the options added/changed, and one for the script name fix in the help output.

2017-04-25 10:10 UTC, hadess commented on lib/flatpak-game.lua
> +    print('Verifying game file.')
I don't want output on stdout or stderr in the scripts. And it's badly indented.

2017-04-25 10:10 UTC, hadess commented on lib/flatpak-game.lua
> +    print('Verifying game file.')
Ditto.

2017-04-25 10:10 UTC, hadess commented on lib/flatpak-game.lua
> +    print('Building repository for ' .. metadata.id)
Ditto.

2017-04-25 10:10 UTC, hadess commented on lib/flatpak-game.lua
> +        if not build_bundle(metadata.id) then
Indentation again.

2017-04-25 10:10 UTC, hadess commented on lib/flatpak-game.lua
> +	if not options.keep_build_dir then
Explanation as to why you're moving this in the commit message please.

2017-04-25 10:10 UTC, hadess commented on game-to-flatpak
> +
Please. no white space changes without justification (no reason to change it here...)

2017-04-25 10:10 UTC, hadess commented on game-to-flatpak
> +        elseif string.sub(v, 1, 7) == '--repo=' then
Indentation. This is at the same level as the `--` check within the for loop in the review tool...

2017-04-25 10:10 UTC, hadess commented on game-to-flatpak
> +    options.keep_repo_dir = true
It might have been a good idea to set `options.repo_dir` to something so that later...

2017-04-25 10:10 UTC, hadess commented on lib/flatpak-game.lua
> +            remove_dir(options.repo_dir)
... like here, where you might be calling remove_dir() with an unset string.

2017-04-25 10:10 UTC, hadess commented on README.md
> +You can define which repo to add the game to by using the `--repo` option:
Please expand "repo" to repository if you're going to use it as a word.

2017-04-25 10:10 UTC, hadess commented on README.md
> +it, it can be found with:
What if we already added another game to the repo, and there's more than one?

2017-04-25 10:10 UTC, hadess commented on README.md
> +be found with:
Please merge into earlier patch.

2017-04-25 10:10 UTC, hadess commented on lib/flatpak-game.lua
> -    print('Verifying game file.')
Again, I don't need to see the stream of thought, so please merge any changes that you're correcting later directly in the original patch where you're modifying it.

2017-04-27 21:28 UTC, andklapp commented on game-to-flatpak
> +    options.keep_repo_dir = true
I do actually set `options.repo_dir` to 'repo', but only if it is empty in the if block right above that one. These two lines are only executed if it is set and `options.keep_repo_dir` is not set. Did I miss something?

2017-04-27 22:08 UTC, andklapp commented on lib/flatpak-game.lua
> +    print('Building repository for ' .. metadata.id)
If it doesn't print the name in the library, should it be passed back to the calling script somehow? How does the user know which game was newly added to the repository? Does this program expect the user to grep through `flatpak remote-ls` output?

2017-04-27 22:18 UTC, andklapp commented on lib/flatpak-game.lua
> +    print('Verifying game file.')
Which indentation convention are you following? I see tab characters, but also some indentations that are spaces, and a few that are tabs *and* spaces, while the Lua documentation says to use two spaces.

2017-05-08 19:25 UTC, hadess commented
Could you please rebase your changes? They do not apply any more.

2017-05-16 10:09 UTC, hadess commented on lib/flatpak-game.lua
> +    print('Verifying game file.')
We use 8-spaces tabs, along with spaces to align arguments. I don't think there are any cases where we only use spaces in our own code, but I'd take a patch that removed the use of those.

2017-05-16 10:11 UTC, hadess commented on lib/flatpak-game.lua
> +    print('Building repository for ' .. metadata.id)
Passing it back to the caller would be nice indeed, but printing in random places in the library is not...

2017-07-12 22:51 UTC, closed without merging